version: '3.0'
services:
  storage:
    restart: always
    image: minio/minio:latest
    command: server /export
    volumes:
      - ./data/minio:/export
      - ./config/minio:/root/.minio
  webp-proxy:
    restart: always
    image: ykzts/webp-proxy:edge
    command: webp-proxy -port 8080 -upstream-url http://storage:9000
    depends_on:
      - storage
  cache:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - storage
      - webp-proxy
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - ./public:/var/www/html:ro
